stages:
  - analyze
  - build
  - test
  - deploy

image: docker-stable

variables:
  PYTEST_COVERAGE_TARGET: .

include:
  - https://ci-files.skypicker.com/templates/build/black.yml
  - https://ci-files.skypicker.com/templates/test/pytest.yml
  - https://ci-files.skypicker.com/templates/build/kaniko.yml
  - https://ci-files.skypicker.com/tags/gke_k8s_deploy_v2/deploy/.gke_k8s_deploy.yml

black:
  stage: analyze

pytest:
  before_script:
    - apk add --no-cache build-base
    - pip install -r test-requirements.txt
    - cd rlock

container:
  extends: .kaniko-build

production:
  extends: .gke_k8s_deploy
  stage: deploy
  variables:
    KUSTOMIZE_K8S_DIR: "./k8s"
    KUSTOMIZE_OVERLAY_NAME: "production"
  before_script:
    - kubectl delete jobs --all
  environment:
    name: rlock-prod
  only:
    - master
