stages:
  - analyze
  - build
  - test
  - deploy

image: docker-stable

variables:
  PYTEST_COVERAGE_TARGET: .

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

include:
  - https://ci-files.skypicker.com/templates/v2/format/black.yml
  - https://ci-files.skypicker.com/templates/v2/format/style.commit.yml
  - https://ci-files.skypicker.com/templates/v2/test/pytest.yml
  - https://ci-files.skypicker.com/templates/v2/build/kaniko.yml
  - https://ci-files.skypicker.com/templates/v2/release/k8s.gke.src.yml

black:
  stage: analyze

pytest:
  services:
    - redis
  allow_failure: true
  before_script:
    - apk add --no-cache build-base
    - pip install -r test-requirements.txt
    - cd rlock

production:
  extends: .k8s-gke-deploy
  stage: deploy
  variables:
    KUSTOMIZE_K8S_DIR: "./k8s"
    KUSTOMIZE_OVERLAY_NAME: "production"
  before_script:
    - kubectl delete jobs --all
  environment:
    name: rlock-prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - when: never
