---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlock
  namespace: rlock
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: 700m
            memory: 700M
          requests:
            cpu: 50m
            memory: 500M
