apiVersion: v1
kind: Service
metadata:
  name: rlock
spec:
  type: ClusterIP
  selector:
    name: rlock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
