#######
# DELETE THIS FILE ONCE COPIED INTO YOUR PROJECT'S .gitlab-ci.yml FILE
# PLEASE REVIEW AFTER COPY, UNCOMMENT "only:", "when:" as you prefer
#######

# needed stages
stages:
  - review
  - deploy

# k8s_deploy CI/CD template
# docs - https://gitlab.skypicker.com/platform/software/gitlab-ci-templates/#deployk8s_deploy
include:
  - 'https://ci-files.skypicker.com/tags/gke_k8s_deploy_v2/deploy/.gke_k8s_deploy.yml'

# review apps job
review:
  extends: .gke_k8s_deploy_review
  stage: review
  variables:
    KUSTOMIZE_K8S_DIR: "./k8s/rlock"
  environment:
    name: review/$CI_COMMIT_REF_SLUG # review can be replaced for any prefix
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN # set KUBE_INGRESS_BASE_DOMAIN in project's cluster integration
    on_stop: stop-review

stop-review:
  extends: .gke_k8s_stop_review
  stage: review
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop

# dev/production/canary jobs
dev:
  extends: .gke_k8s_deploy
  stage: deploy
  #when: manual
  variables:
    KUSTOMIZE_K8S_DIR: "./k8s/rlock"
    KUSTOMIZE_OVERLAY_NAME: "dev"
  environment:
    name: dev # needs to match k8s integration environment scope
    #url: https://dev.kiwi.com

production:
  extends: .gke_k8s_deploy
  stage: deploy
  variables:
    KUSTOMIZE_K8S_DIR: "./k8s/rlock"
    KUSTOMIZE_OVERLAY_NAME: "production"
  environment:
    name: production # needs to match k8s integration environment scope
    #url: https://www.kiwi.com
  only:
    - master


